

import Head from 'next/head';
import Container from 'react-bootstrap/Container'
import Navigation from '../components/navigation'
import Login  from '../components/login';

export default function Home() {
  return (
    <main className='d-flex flex-column min-vh-100'>
      <Head>
        <title>Clinica internacional - SGP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Login> </Login>

      {/* <Navigation> </Navigation> */}
    </main>
  );
}



