

import Head from 'next/head';
import Container from 'react-bootstrap/Container'

export default function Login() {
  return (
    <main className='d-flex flex-column min-vh-100'>
      <Head>
        <title>Clinica internacional - SGP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <body>
        <div class = "container-fluid">
          <div class="row">
            <div class="offset-md-2 col-lg-5 col-md-7 offset-lg-4 offset-md-3">
              <div class="panel border bg-white">
                <div class="panel-heading">
                    <h3 class="pt-3 font-weight-bold">Ingreso al sistema</h3>
                </div>
                <div class="panel-body p-3">
                    <form action="login_script.php" method="POST">
                        <div class="form-group py-2">
                            <div class="input-field"> <span class="far fa-user p-2"></span> <input type="text" placeholder="ID de usuario" required/> </div>
                        </div>
                        <div class="form-group py-1 pb-2">
                            <div class="input-field"> <span class="fas fa-lock px-2"></span> <input type="password" placeholder="Ingrese su contraseña" required/> <button class="btn bg-white text-muted"> <span class="far fa-eye-slash"></span> </button> </div>
                        </div>
                        <div class="form-inline"> <input type="checkbox" name="remember" id="remember"/> <label for="remember" class="text-muted">Recordarme</label> </div>
                        <div><a href="#" id="forgot" class="font-weight-bold">¿Olvidó su contraseña?</a> </div>
                        <div class="btn btn-primary btn-block mt-3">Ingreso</div>
                        {/* <div class="text-center pt-4 text-muted">¿No tienes una cuenta? <a href="#">Registrese</a> </div> */}
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </main>
  );
}



